export const GET_ALL_CATEGORY_START = 'GET_ALL_CATEGORY_START';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_ERROR = 'GET_ALL_CATEGORY_ERROR';

export const GET_LIST_ADMIN_CATEGORY_START = 'GET_LIST_ADMIN_CATEGORY_START';
export const GET_LIST_ADMIN_CATEGORY_SUCCESS = 'GET_LIST_ADMIN_CATEGORY_SUCCESS';
export const GET_LIST_ADMIN_CATEGORY_ERROR = 'GET_LIST_ADMIN_CATEGORY_ERROR';

export const CREATE_NEW_CATEGORY_START = 'CREATE_NEW_CATEGORY_START';
export const CREATE_NEW_CATEGORY_SUCCESS = 'CREATE_NEW_CATEGORY_SUCCESS';
export const CREATE_NEW_CATEGORY_ERROR = 'CREATE_NEW_CATEGORY_ERROR';

export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';

export const SEARCH_CATEGORY_START = 'SEARCH_CATEGORY_START';
export const SEARCH_CATEGORY_SUCCESS = 'SEARCH_CATEGORY_SUCCESS';
export const SEARCH_CATEGORY_ERROR = 'SEARCH_CATEGORY_ERROR';

export const GET_LIST_ADMIN_GAME_START = 'GET_LIST_ADMIN_GAME_START';
export const GET_LIST_ADMIN_GAME_SUCCESS = 'GET_LIST_ADMIN_GAME_SUCCESS';
export const GET_LIST_ADMIN_GAME_ERROR = 'GET_LIST_ADMIN_GAME_ERROR';

export const CREATE_NEW_GAME_START = 'CREATE_NEW_GAME_START';
export const CREATE_NEW_GAME_SUCCESS = 'CREATE_NEW_GAME_SUCCESS';
export const CREATE_NEW_GAME_ERROR = 'CREATE_NEW_GAME_ERROR';

export const GET_ALL_PLATFORM_START = 'GET_ALL_PLATFORM_START';
export const GET_ALL_PLATFORM_SUCCESS = 'GET_ALL_PLATFORM_SUCCESS';
export const GET_ALL_PLATFORM_ERROR = 'GET_ALL_PLATFORM_ERROR';

export const GET_GAME_DETAIL_START = 'GET_GAME_DETAIL_START';
export const GET_GAME_DETAIL_SUCCESS = 'GET_GAME_DETAIL_SUCCESS';
export const GET_GAME_DETAIL_ERROR = 'GET_GAME_DETAIL_ERROR'

export const UPDATE_GAME_START = 'UPDATE_GAME_START';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';
export const UPDATE_GAME_ERROR = 'UPDATE_GAME_ERROR';


