export const GET_LIST_HOME_CATEGORY_START = "GET_LIST_HOME_CATEGORY_START";
export const GET_LIST_HOME_CATEGORY_SUCCESS = "GET_LIST_HOME_CATEGORY_SUCCESS";
export const GET_LIST_HOME_CATEGORY_ERROR = "GET_LIST_HOME_CATEGORY_ERROR";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_HOME_GAME_START = "GET_HOME_GAME_START";
export const GET_HOME_GAME_SUCCESS = "GET_HOME_GAME_SUCCESS";
export const GET_HOME_GAME_ERROR = "GET_HOME_GAME_ERROR";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const GET_GAME_BY_CATEGORY_START = "GET_GAME_BY_CATEGORY_START"
export const GET_GAME_BY_CATEGORY_SUCCESS = "GET_GAME_BY_CATEGORY_SUCCESS"
export const GET_GAME_BY_CATEGORY_ERROR = "GET_GAME_BY_CATEGORY_ERROR"





